### ISSUE TITLE
h5和小程序公用一个dist

### ISSUE THREAD

**Issue by hgt803** [luyixin/compatible#2]
不能同时开发

**Comment by hgt803** [comment]
build_web/webpack.base.conf.js
  line:13
      -  fse.removeSync(resolve('dist_web'))
      + fse.removeSync(resolve('dist_web'))

config_web/index.js
   line:46
       -  index: path.resolve(__dirname, '../dist/index.html'),
       + index: path.resolve(__dirname, '../dist_web/index.html'),
  line:49
       -  assetsRoot: path.resolve(__dirname, '../dist'),
       + assetsRoot: path.resolve(__dirname, '../dist_web'),

**Comment by luyixin** [comment]
如果要两端同时开发的话，可以把fse删除dist文件夹的代码，搬到webpack.prod.conf.js里面，在dev环境不做删除处理。我是自己习惯删除dist文件夹，因为目前没有处理缓存的问题。

**Comment by luyixin** [comment]
要做到两端开发的话，业务上还需要做兼容性处理，比如小程序和公众号api不一样，需要自己写代码兼容哦。目前我这边公司项目，已经业务成型。
