### ISSUE TITLE
yarn版本问题

### ISSUE THREAD

**Issue by hgt803** [luyixin/compatible#3]
使用npm安装依赖包因为有lock所以没问题。yarn安装就会因为webpack版本过高而报错

**Comment by hgt803** [comment]
"webpack": "^3.11.0",

**Comment by luyixin** [comment]
目前我本地没有装yarn，yarn没有测试哈，过段时间，我有时间了，会在后续的优化工作里面处理这个问题

**Comment by luyixin** [comment]
目前已增加对yarn的支持和兼容，谢谢关注
